name: Minify Workflow
on:
  push:
    branches: main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: jossydevers/minify-js@v1.0.0
      with:
        directory: 'rule34_xxx/index.js' # (OPTIONAL)
        output: 'minify/rule34_xxx.min.js' # (OPTIONAL)

    - uses: stefanzweifel/git-auto-commit-action@v5
