name: Minify Workflow
on:
  push:
    branches: main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: HTML/CSS/JS Minifier
      uses: docker://devatherock/minify-js:3.1.0
      with:
        directory: 'rule34_xxx'      # Optional
        output: 'minify/src'  # Optional

    - uses: stefanzweifel/git-auto-commit-action@v5
