name: Minify Workflow
on:
  push:
    branches: main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: HTML/CSS/JS Minifier
      uses: devatherock/minify-js@v3.1.0
      with:
        directory: 'rule34_xxx/index.js' # (OPTIONAL)
        output: 'minify/rule34_xxx' # (OPTIONAL)

    - uses: stefanzweifel/git-auto-commit-action@v5
